#!/usr/bin/env bash
# sets up the api to be exposed by nginx

set -eo pipefail; [[ $FIGURE_TRACE ]] && set -x

APP="$1"; PORT="$2"; IP="$3"

API="api";

echo "upstream $APP$API { server $IP:$((PORT-1)); }" > tmpfile
cat $FIGURE_ROOT/$APP/nginx.conf >> tmpfile
mv tmpfile $FIGURE_ROOT/$APP/nginx.conf

nginx -t
